name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Lint code
      run: |
          pip install pylint
          pylint **/*.py --output-format=json > pylint-report.json || true
          score=$(jq 'map(select(.type == "error")) | length' pylint-report.json)
          echo "Pylint score (error count): $score"
          if [ "$score" -gt 8 ]; then
            echo "Pylint score is below 8. Failing the job."
            exit 1
          fi

    - name: Build Docker image
      run: docker build -t adityadrex/calculator:latest .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push adityadrex/calculator:latest
