name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Lint code
      run: pip install pylint && pylint app/main.py

    - name: Build Docker image
      run: docker build -t Aditya-d-r/calculator:latest .

    - name: Push Docker image to DockerHub
      run: docker push Aditya-d-r/calculator:latest
